### ISSUE TITLE
Add support for bullet character

### ISSUE THREAD

**Issue by simark** [eepp/jome#20]
My employer requires me to be able to type [bullet characters](https://www.compart.com/en/unicode/U+2022), please kindly add support for this.  I need this feature quickly, ideally before the end of the week.  Thanks in advance.

**Comment by eepp** [comment]
Sorry, jome only works with the emoji codepoints, above U+1F000.

You might want to suggest to your employer to use 🥑 instead of bullet points.

You might also consider [Rofi](https://github.com/davatorium/rofi) to achieve what you need, or simply assign a dedicated keyboard shortcut to:

    xdotool type •

Closing this!
